```{r setup}
# rm(list = ls())
source("~/Spatial/.RProfile")
library(configr)
configr::read.config()
devtools::load_all("~/fstutils/", export_all = TRUE)
devtools::load_all("~/Spatial/FEMA/femar", reset=TRUE, export_all = TRUE)
print(getOption("tigris_year"))
# source("~/lattice_setup.R")
library(readr)

library(survey)
browseURL("https://r-survey.r-forge.r-project.org/survey/")
stop()
browseURL(.EIA_workdir)
list.files(.EIA_datadir, full.names = TRUE, recursive = TRUE)
#dir.create(.EIA_workdir)
?strOptions
strOptions()

# https://www.eia.gov/consumption/residential/

# TYPEHUQ
# 1 Mobile home
# 2 Single-family house detached from any other house
# 3 Single-family house attached to one or more other houses (for example: duplex, row house, or townhome)
# 4 Apartment in a building with 2 to 4 units
# 5 Apartment in a building with 5 or more units

RECS2020 <- get_RECS2020()
dim(RECS2020)
# Total number of households
RECS2020[, .(NWEIGHT=sum(NWEIGHT))]

str(RECS2020$TYPEHUQ)

# ?fct_recode
# RECS2020$TYPEHUQ <- fct_recode()



attach(RECS2020)
RECS2020[, table(TYPEHUQ, useNA = "ifany")]
detach(RECS2020)

# recs_mf <- RECS2020[TYPEHUQ=="5"]
# recs_mf%>% as_tibble()
#
# recs_mf[, .(.N), keyby = c('STATE_FIPS','KOWNRENT')]
# (recs_mf_zz <- recs_mf[, .(.N), keyby = c('KOWNRENT')])

# RECS2020[, .(.N, BTUNG=weighted.mean(BTUNG,NWEIGHT), BTUEL=weighted.mean(BTUEL,NWEIGHT))]



```

```{r Climate}
RECS2020[, .(CLIMATE_REGION, BA_CLIMATE, IECC_CLIMATE_CODE)]

RECS2020[, table(CLIMATE_REGION, useNA = "ifany")]
RECS2020[, table(BA_CLIMATE, useNA = "ifany")]
RECS2020[, table(IECC_CLIMATE_CODE, useNA = "ifany")]

```

# Calculate the frequency and RSE of households that used natural gas as their main space-heating fuel (Table HC6.1)


```{r Natural_Gas}
## Step 1 ----

# Create a new variable to flag the records of households that used
# natural gas as their main space-heating fuel. This new variable
# NG_MAINSPACEHEAT is equal to 1 if the household used natural gas as its main
# space-heating fuel and 0 otherwise.

# grep("HEAT", names(RECS2020), value = TRUE)

# FUELHEAT
# 5 Electricity
# 1 Natural gas from underground pipes
# 2 Propane (bottled gas)
# 3 Fuel oil
# 7 Wood or pellets
# 99 Other
# -2 Not applicable

RECS2020$NG_MAINSPACEHEAT <- ifelse(RECS2020$FUELHEAT == 1, 1, 0)

## Step 2. ----

# Define the Jackknife replicate weights you will use for estimation:
(repweights<-select(RECS2020,NWEIGHT1:NWEIGHT60))

## Step 3. ----

# Number of household that use NG heating in main space
RECS2020[, .(NG_MAINSPACEHEAT=sum(NG_MAINSPACEHEAT*NWEIGHT))]%>% as_tibble()

# percent of household that use NG
RECS2020[, weighted.mean(NG_MAINSPACEHEAT,NWEIGHT)]

# Number of household that use NG heating in main space per property type
RECS2020[, .(NG_MAINSPACEHEAT=sum(NG_MAINSPACEHEAT*NWEIGHT),NWEIGHT=sum(NWEIGHT)), keyby = .(TYPEHUQ)]%>% as_tibble()

# Define the survey design with the Jackknife replicate weights to calculate
# appropriate standard errors uising `svrepdesign`:
?svrepdesign
(RECS <- svrepdesign(data = RECS2020,
                     weight = ~NWEIGHT,
                     repweights = repweights,
                     type = "JK1",
                     combined.weights = TRUE,
                     scale = (ncol(repweights)-1)/ncol(repweights),
                     mse = TRUE))
summary(RECS)
class(RECS)
methods(class="svyrep.design")
dim(RECS)



library(weights)
help(package="weights")
weights(RECS) %>% colSums() %>% as_tibble()# total number of household

## Step 4. ----

# Use `svytotal` to sum the number of households by `NG_MAINSPACEHEAT`, using the survey design defined above.
# debugonce(svytotal)
?svytotal
(NG_MAINSPACEHEAT_Total<-as.data.frame(svytotal(~NG_MAINSPACEHEAT,RECS)))
RECS2020[, .(NG_MAINSPACEHEAT=sum(NG_MAINSPACEHEAT*NWEIGHT))]%>% as_tibble()
# Answer. The estimated total households that used natural gas as their main
# space-heating fuel is 62,713,449 households. The calculation for the RSE is
# (483,047 / 62,713,449)*100 = 0.77. The sampling error is less than 1% of the
# estimate, which is relatively small. Alternatively, the RSE can be derived
# from:
(NG_MAINSPACEHEAT_Total$RSE<-(NG_MAINSPACEHEAT_Total$SE/NG_MAINSPACEHEAT_Total$total)*100)

# To obtain the proportion estimate, use the `svymean()` function instead of the `svytotal` in the expression in Step 4. In addition, the confint() function provides the 95% confidence limits.
svymean(~NG_MAINSPACEHEAT,RECS)

```

```{r R Example 2}
# https://www.eia.gov/consumption/residential/data/2020/state/pdf/ce4.1.ng.st.pdf
# Calculate the sum and average of the total natural gas used for the households
# in South Carolina (SC) (Table CE4.1.NG.ST Annual household site natural gas
# consumption in the United States by end use – totals and percentages, 2020).
# To calculate the total consumption estimates in R, use the svytotal()
# function; and use the `svymean()` function for the average consumption . In
# addition, use `svyby()` to group households by USENG and state (STATE_POSTAL)
# and the `subset()` function to limit the results to SC only.

# First, create a new variable to flag the households that have positive natural
# gas consumption for any natural gas end use. This new variable NGUSE is equal
# to 1 if BTUNG is greater than 0 and 0 otherwise. Then, run the survey design
# for the dataset again before producing estimates using the functions mentioned
# above.

RECS2020$NGUSE <- ifelse(RECS2020$BTUNG > 0, 1,0)
(RECS <- svrepdesign(data = RECS2020,
                    weight = ~NWEIGHT,
                    repweights = repweights,
                    type = "JK1",
                    combined.weights = TRUE,
                    scale = (ncol(repweights)-1)/ncol(repweights),
                    mse = TRUE)
)

# calculate the total:
(BTUNG_TOTAL<-svyby(~BTUNG, by=~STATE_POSTAL+NGUSE, RECS, svytotal))
(BTUNG_SCTOTAL<-subset(BTUNG_TOTAL, STATE_POSTAL=='SC')) %>% as_tibble # trillion BTU


# The output below shows the result for SC. The total estimated consumption for
# households that used natural gas in SC is 26.2 trillion British thermal units
# (Btu). The RSE for the total is ( 2509266634/26220994238)*100 = 9.6%.

# calculate the mean:
(BTUNG_MEAN<-svyby(~BTUNG, by=~STATE_POSTAL+NGUSE, RECS, svymean))
(BTUNG_SCMEAN<-subset(BTUNG_MEAN, STATE_POSTAL=='SC'))

# The average consumption per household is 34.4 million BTU, with RSE=6.3. As
# mentioned in R example 1, the 95% confidence limits with the `conflint()`
# function. Note that the estimates for NGUSE = 0 reflect consumption for homes
# that do not use any natural gas.


```

```{r R Example 3}

# Calculate the energy intensity per square foot by climate zone for the United
# States (Table CE1.1)

# https://www.eia.gov/consumption/residential/data/2020/c&e/pdf/ce1.1.pdf

## Step 1. ----

#Create a new variable called CLIMATE_REGION to combine climate zones, and rerun
#the survey design RECS.
RECS2020$CLIMATE_REGION <- as.factor(ifelse(RECS2020$BA_CLIMATE=='Subarctic', 'Very cold/Cold',
                                            ifelse(RECS2020$BA_CLIMATE=='Very-Cold', 'Very cold/Cold',
                                                   ifelse(RECS2020$BA_CLIMATE=='Cold', 'Very cold/Cold',
                                                          ifelse(RECS2020$BA_CLIMATE=='Mixed-Humid', 'Mixed-humid',
                                                                 ifelse(RECS2020$BA_CLIMATE=='Mixed-Dry', 'Mixed-dry/Hot-dry',
                                                                        ifelse(RECS2020$BA_CLIMATE=='Hot-Dry', 'Mixed-dry/Hot-dry',
                                                                               ifelse(RECS2020$BA_CLIMATE=='Hot-Humid', 'Hot-humid',
                                                                                      ifelse(RECS2020$BA_CLIMATE=='Marine', 'Marine', NA)))))))))
(RECS <- svrepdesign(data = RECS2020,
                     weight = ~NWEIGHT,
                     repweights = repweights,
                     type = "JK1",
                     combined.weights = TRUE,
                     scale = (ncol(repweights)-1)/ncol(repweights),
                     mse = TRUE))

## Step 2 ----

# To calculate the energy intensity per square foot for all U.S. homes, use the
# `svyratio()` function.
(BTUPERSQFT<-svyratio(~TOTALBTU, ~TOTSQFT_EN, RECS))

# The national estimate for energy intensity per square foot is about 42,000
# Btu, as shown in Table CE1.1. The RSE is (0.1801853/42.20056)*100 = 0.43.

#To calculate the regional energy intensity per square foot, use `svyratio` with
#`svyby()`.
(BTUPERSQFT_BY_CLIMATE_REGION<-svyby(~TOTALBTU, by=~CLIMATE_REGION,denominator=~TOTSQFT_EN, RECS, svyratio))

# As an example, the average total consumption per square foot in the hot-humid
# climate is about 35,000 Btu, as shown in the table below.

```

```{r R Example 4}

#Compare if the proportions and the consumption means for households using
#natural gas as their main space-heating fuel are statistically different among
#the households in different Census regions. To compare if the proportions of
#households using natural gas as their main space-heating fuel are different
#among the Census regions, use the `svychisq()` function to obtain chi-square
#statistics.
?svyby
# BTU per Sqft by census region
? svyratio
?svymean
?svytotal
(BTUPERSQFT_BY_REGIONC<-svyby(formula = ~TOTALBTU, by=~REGIONC,denominator=~TOTSQFT_EN
                              , design = RECS, FUN=svyratio))


(NGSPH_CHISQ<-svychisq(~NG_MAINSPACEHEAT+REGIONC,design=RECS,statistic="Chisq"))
class(NGSPH_CHISQ)
methods(class="htest")

# To compare if the average space-heating consumption estimates for households
# using natural gas as their main space-heating fuel are different among the
# Census regions, use the svyglm() function to run a regression model and obtain
# the coefficient, and use the regTermTest() function to obtain the F-statistic.
(RECS_NGSPH<-subset(RECS,NG_MAINSPACEHEAT==1))
svytotal(x = ~TOTALBTUSPH,design = RECS_NGSPH)

(NGSPH_REGIONGLM<-svyglm(TOTALBTUSPH~factor(REGIONC), design=RECS_NGSPH))

(regTermTest(NGSPH_REGIONGLM, ~factor(REGIONC), method="Wald"))


```

```{r cleanup}

save.image(file = file.path(NRI_WORKDIR, "run_EIA.RData"))

# Notes to Consider When Using the Microdata File and Replicate Weights
# 1. Publication standards: We do not publish RECS estimates where the RSE is higher than 50 or the number of households used for the calculation is less than 10 (indicated by a Q in the data tables). We recommend following these guidelines for custom analysis using the public use microdata file.
# 2. Imputation variables: We imputed most variables for Don’t Know and Refuse responses. The Z variables, also referred to as imputation flags, are in the public use microdata file. The imputation flag indicates whether we based the corresponding non-Z variable was reported data (Z variable = 0) or if we imputed it (Z variable = 1). Variables from the RECS questionnaire that we did not impute, contained no missing data, or were not from the questionnaire have no corresponding Z variables. We recommend using the imputed data, where available, to avoid biased estimation.
# 3. Standardized coding: Variables that we did not ask all respondents use the response code –2 for Not Applicable. For example, respondents who answered that they did not use any televisions at home (TVCOLOR = 0) were not asked what size television they most use at home, so TVSIZE1 = -2. Use caution when performing calculations on variables that have -2 responses.
# 4. Indicator variables: The microdata file contains variables to indicate the use of major fuels and specific end uses within each housing unit for 2020. We derived these variables from answers given by each respondent, and they indicate whether the respondent had access to the fuel, used the fuel, and engaged in a specific end use. All indicators are either a 0 or a 1 for each combination of major fuel and end use. For example, respondents who say they heated their homes with electricity in 2020 will have the derived variable ELWARM = 1. If respondents say they have equipment but did not use it, the corresponding indicator is 0. As an example, respondents in a warm climate might have heating equipment but did not use it in 2020. For this case, ELWARM is 0.
# 5. Confidentiality: We collected the 2020 RECS under the authority of the Confidential Information Protection and Statistical Efficiency Act (CIPSEA). The agency, project staff, and our contractors and agents are personally accountable for protecting the identity of individual respondents. We took the following steps to avoid disclosing personally identifiable information in the public-use microdata file.
# June 2023
# U.S. Energy Information Administration | Using the Microdata File to Compute Estimates and Standard Errors 14
# • We removed local geographic identifiers of sampled housing units, such as addresses.
# • We removed the following variables because we received too few responses or because we found a disclosure risk:
#   – COMBINED (on-site combined heat and power)
# – WIND (on-site wind generation)
# – PVINSTALL (year photovoltaic solar [PV] was installed)
# – PVCAPACITY (capacity of PV system in kilowatts)
# – APTEVCHG (do respondents in apartment building with 5+ units have access to an electric vehicle [EV] charger)
# – EVMAKE, EVMODEL, EVYEAR (EV make, model, and year)
# – EVCHRGAPT, EVCHRGWKS, EVCHRGBUS, EVCHRGMUNI, EVCHRGHWY, EVHCRGOTH (respondent charged an EV at their apartment building, place of work, a business or shopping center, a municipal parking lot, a highway rest stop, a car dealership, or somewhere else)
# – EVHOMEAMT (what percentage of EV charging was done at home)
# – EVCHRGTYPE (what type of EV charger does respondent have at home)
# – EVWRKMILES (average number of miles EV is driven a week)
# • The following variables were top-coded:
#   – BEDROOMS (number of bedrooms) to 6
# – OTHROOMS (number of other rooms) to 9
# – NCOMBATH (number of full bathrooms) to 4
# – NHAFBATH (number of half bathrooms) to 2
# – HHAGE (age of the householder) to 90
# – NHSLDMEM (number of household members) to 7
# – NUMCHILD (number of children under 18) to 4
# • We added random errors to weather and climate (HDD30YR and CDD30YR) values, as well as to the annualized consumption variables for electricity and natural gas.
# June 2023
# Adjustments were minor and do not result in significant differences for aggregate estimation.
# • We rounded the SQFTEST, TOTSQFT_EN, TOTHSQFT, and TOTCSQFT variables to the nearest 10.

# References
# Lohr, S.L. (2010). Sampling: Desing and Analysis. 2nd ed. Boston: Brooks/Cole. Page 380–383.
# Lumley, T. (2017) "Survey: analysis of complex survey samples". R package version 4.1-1.
```
