
utils::globalVariables(c("STORM_CATEGORY", "MINIMUM_WIND_SPEED_MPH", "MAXIMUM_WIND_SPEED_MPH",
  "MINIMUM_WIND_SPEED_KTS", "MAXIMUM_WIND_SPEED_KTS", "AVERAGE_RADIUS_OF_HURRICANE_OR_TROPICAL_STORM_FORCE_WINDS_MILES",
  "USA_SSHS"))
