
# NRI by state ------------------------------------------------------------


utils::globalVariables(c("OID_", "NRI_ID", "STATE", "STATEABBRV", "STATEFIPS", "POPULATION",
                         "BUILDVALUE", "AGRIVALUE", "AREA", "EAL_SCORE", "EAL_RATNG",
                         "EAL_VALT", "EAL_VALB", "EAL_VALP", "EAL_VALPE", "EAL_VALA",
                         "ALR_VALB", "ALR_VALP", "ALR_VALA", "ALR_NPCTL", "AVLN_EVNTS",
                         "AVLN_EXP_AREA", "AVLN_EXPB", "AVLN_EXPP", "AVLN_EXPPE", "AVLN_EXPT",
                         "AVLN_EALB", "AVLN_EALP", "AVLN_EALPE", "AVLN_EALT", "AVLN_EALS",
                         "AVLN_EALR", "AVLN_ALRB", "AVLN_ALRP", "AVLN_ALR_NPCTL", "CFLD_EVNTS",
                         "CFLD_EXP_AREA", "CFLD_EXPB", "CFLD_EXPP", "CFLD_EXPPE", "CFLD_EXPT",
                         "CFLD_EALB", "CFLD_EALP", "CFLD_EALPE", "CFLD_EALT", "CFLD_EALS",
                         "CFLD_EALR", "CFLD_ALRB", "CFLD_ALRP", "CFLD_ALR_NPCTL", "CWAV_EVNTS",
                         "CWAV_EXP_AREA", "CWAV_EXPB", "CWAV_EXPP", "CWAV_EXPPE", "CWAV_EXPA",
                         "CWAV_EXPT", "CWAV_EALB", "CWAV_EALP", "CWAV_EALPE", "CWAV_EALA",
                         "CWAV_EALT", "CWAV_EALS", "CWAV_EALR", "CWAV_ALRB", "CWAV_ALRP",
                         "CWAV_ALRA", "CWAV_ALR_NPCTL", "DRGT_EVNTS", "DRGT_EXP_AREA",
                         "DRGT_EXPA", "DRGT_EXPT", "DRGT_EALA", "DRGT_EALT", "DRGT_EALS",
                         "DRGT_EALR", "DRGT_ALRA", "DRGT_ALR_NPCTL", "ERQK_EVNTS", "ERQK_EXP_AREA",
                         "ERQK_EXPB", "ERQK_EXPP", "ERQK_EXPPE", "ERQK_EXPT", "ERQK_EALB",
                         "ERQK_EALP", "ERQK_EALPE", "ERQK_EALT", "ERQK_EALS", "ERQK_EALR",
                         "ERQK_ALRB", "ERQK_ALRP", "ERQK_ALR_NPCTL", "HAIL_EVNTS", "HAIL_EXP_AREA",
                         "HAIL_EXPB", "HAIL_EXPP", "HAIL_EXPPE", "HAIL_EXPA", "HAIL_EXPT",
                         "HAIL_EALB", "HAIL_EALP", "HAIL_EALPE", "HAIL_EALA", "HAIL_EALT",
                         "HAIL_EALS", "HAIL_EALR", "HAIL_ALRB", "HAIL_ALRP", "HAIL_ALRA",
                         "HAIL_ALR_NPCTL", "HWAV_EVNTS", "HWAV_EXP_AREA", "HWAV_EXPB",
                         "HWAV_EXPP", "HWAV_EXPPE", "HWAV_EXPA", "HWAV_EXPT", "HWAV_EALB",
                         "HWAV_EALP", "HWAV_EALPE", "HWAV_EALA", "HWAV_EALT", "HWAV_EALS",
                         "HWAV_EALR", "HWAV_ALRB", "HWAV_ALRP", "HWAV_ALRA", "HWAV_ALR_NPCTL",
                         "HRCN_EVNTS", "HRCN_EXP_AREA", "HRCN_EXPB", "HRCN_EXPP", "HRCN_EXPPE",
                         "HRCN_EXPA", "HRCN_EXPT", "HRCN_EALB", "HRCN_EALP", "HRCN_EALPE",
                         "HRCN_EALA", "HRCN_EALT", "HRCN_EALS", "HRCN_EALR", "HRCN_ALRB",
                         "HRCN_ALRP", "HRCN_ALRA", "HRCN_ALR_NPCTL", "ISTM_EVNTS", "ISTM_EXP_AREA",
                         "ISTM_EXPB", "ISTM_EXPP", "ISTM_EXPPE", "ISTM_EXPT", "ISTM_EALB",
                         "ISTM_EALP", "ISTM_EALPE", "ISTM_EALT", "ISTM_EALS", "ISTM_EALR",
                         "ISTM_ALRB", "ISTM_ALRP", "ISTM_ALR_NPCTL", "LNDS_EVNTS", "LNDS_EXP_AREA",
                         "LNDS_EXPB", "LNDS_EXPP", "LNDS_EXPPE", "LNDS_EXPT", "LNDS_EALB",
                         "LNDS_EALP", "LNDS_EALPE", "LNDS_EALT", "LNDS_EALS", "LNDS_EALR",
                         "LNDS_ALRB", "LNDS_ALRP", "LNDS_ALR_NPCTL", "LTNG_EVNTS", "LTNG_EXP_AREA",
                         "LTNG_EXPB", "LTNG_EXPP", "LTNG_EXPPE", "LTNG_EXPT", "LTNG_EALB",
                         "LTNG_EALP", "LTNG_EALPE", "LTNG_EALT", "LTNG_EALS", "LTNG_EALR",
                         "LTNG_ALRB", "LTNG_ALRP", "LTNG_ALR_NPCTL", "RFLD_EVNTS", "RFLD_EXP_AREA",
                         "RFLD_EXPB", "RFLD_EXPP", "RFLD_EXPPE", "RFLD_EXPA", "RFLD_EXPT",
                         "RFLD_EALB", "RFLD_EALP", "RFLD_EALPE", "RFLD_EALA", "RFLD_EALT",
                         "RFLD_EALS", "RFLD_EALR", "RFLD_ALRB", "RFLD_ALRP", "RFLD_ALRA",
                         "RFLD_ALR_NPCTL", "SWND_EVNTS", "SWND_EXP_AREA", "SWND_EXPB",
                         "SWND_EXPP", "SWND_EXPPE", "SWND_EXPA", "SWND_EXPT", "SWND_EALB",
                         "SWND_EALP", "SWND_EALPE", "SWND_EALA", "SWND_EALT", "SWND_EALS",
                         "SWND_EALR", "SWND_ALRB", "SWND_ALRP", "SWND_ALRA", "SWND_ALR_NPCTL",
                         "TRND_EVNTS", "TRND_EXP_AREA", "TRND_EXPB", "TRND_EXPP", "TRND_EXPPE",
                         "TRND_EXPA", "TRND_EXPT", "TRND_EALB", "TRND_EALP", "TRND_EALPE",
                         "TRND_EALA", "TRND_EALT", "TRND_EALS", "TRND_EALR", "TRND_ALRB",
                         "TRND_ALRP", "TRND_ALRA", "TRND_ALR_NPCTL", "TSUN_EVNTS", "TSUN_EXP_AREA",
                         "TSUN_EXPB", "TSUN_EXPP", "TSUN_EXPPE", "TSUN_EXPT", "TSUN_EALB",
                         "TSUN_EALP", "TSUN_EALPE", "TSUN_EALT", "TSUN_EALS", "TSUN_EALR",
                         "TSUN_ALRB", "TSUN_ALRP", "TSUN_ALR_NPCTL", "VLCN_EVNTS", "VLCN_EXP_AREA",
                         "VLCN_EXPB", "VLCN_EXPP", "VLCN_EXPPE", "VLCN_EXPT", "VLCN_EALB",
                         "VLCN_EALP", "VLCN_EALPE", "VLCN_EALT", "VLCN_EALS", "VLCN_EALR",
                         "VLCN_ALRB", "VLCN_ALRP", "VLCN_ALR_NPCTL", "WFIR_EVNTS", "WFIR_EXP_AREA",
                         "WFIR_EXPB", "WFIR_EXPP", "WFIR_EXPPE", "WFIR_EXPA", "WFIR_EXPT",
                         "WFIR_EALB", "WFIR_EALP", "WFIR_EALPE", "WFIR_EALA", "WFIR_EALT",
                         "WFIR_EALS", "WFIR_EALR", "WFIR_ALRB", "WFIR_ALRP", "WFIR_ALRA",
                         "WFIR_ALR_NPCTL", "WNTW_EVNTS", "WNTW_EXP_AREA", "WNTW_EXPB",
                         "WNTW_EXPP", "WNTW_EXPPE", "WNTW_EXPA", "WNTW_EXPT", "WNTW_EALB",
                         "WNTW_EALP", "WNTW_EALPE", "WNTW_EALA", "WNTW_EALT", "WNTW_EALS",
                         "WNTW_EALR", "WNTW_ALRB", "WNTW_ALRP", "WNTW_ALRA", "WNTW_ALR_NPCTL",
                         "NRI_VER"))


# Huricane category -------------------------------------------------------


utils::globalVariables(c("STORM_CATEGORY", "MINIMUM_WIND_SPEED_MPH", "MAXIMUM_WIND_SPEED_MPH",
  "MINIMUM_WIND_SPEED_KTS", "MAXIMUM_WIND_SPEED_KTS", "AVERAGE_RADIUS_OF_HURRICANE_OR_TROPICAL_STORM_FORCE_WINDS_MILES",
  "USA_SSHS"))
